apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-lts
        image: jenkins/jenkins:lts
        volumeMounts:
          - name: jenkins-data
            mountPath:  /var/jenkins_home/
        resources:
          limits:
            memory: "5G"
            cpu: "1024m"
        ports:
          - containerPort: 8080
      volumes:
      - name: jenkins-data
        hostPath:
          path:  /data/jenkins/
          type: Directory 